// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'D:/yinKeCode/encode-hooks-tag/encode-hooks-1.0copy/node_modules/.pnpm/dumi@2.4.20_@babel+core@7.27.1_eslint@8.57.1_prettier@3.5.3_react-dom@18.3.1_react@18.3.1_sty_uvz7eawcgpiiesnodpvqyjzx7a/node_modules/dumi/theme-default/slots/Logo/index.js';
