// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { getSketchJSON } from 'D:/yinKeCode/encode-hooks-tag/encode-hooks-1.0copy/.dumi/tmp/plugin-html2sketch';
// plugins types.d.ts
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'D:/yinKeCode/encode-hooks-tag/encode-hooks-1.0copy/node_modules/.pnpm/@umijs+renderer-react@4.4.10_react-dom@18.3.1_react@18.3.1/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from 'D:/yinKeCode/encode-hooks-tag/encode-hooks-1.0copy/node_modules/.pnpm/@umijs+renderer-react@4.4.10_react-dom@18.3.1_react@18.3.1/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'D:/yinKeCode/encode-hooks-tag/encode-hooks-1.0copy/node_modules/.pnpm/umi@4.4.10_@babel+core@7.27.1_eslint@8.57.1_prettier@3.5.3_react-dom@18.3.1_react@18.3.1_sass_ebgxoc73lljig4gfvjyaaubgii/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
