// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from 'D:/yinKeCode/encode-hooks-tag/encode-hooks-1.0copy/docs/guide/index.md?type=frontmatter';
import { demoIndex as dmi0 } from 'D:/yinKeCode/encode-hooks-tag/encode-hooks-1.0copy/docs/guide/index.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from 'D:/yinKeCode/encode-hooks-tag/encode-hooks-1.0copy/docs/index.md?type=frontmatter';
import { demoIndex as dmi1 } from 'D:/yinKeCode/encode-hooks-tag/encode-hooks-1.0copy/docs/index.md?type=demo-index';

export const filesMeta = {
  'docs/guide/index': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/yinKeCode/encode-hooks-tag/encode-hooks-1.0copy/docs/guide/index.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/yinKeCode/encode-hooks-tag/encode-hooks-1.0copy/docs/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
