// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import nprogress from 'D:/yinKeCode/encode-hooks-tag/encode-hooks-1.0copy/node_modules/.pnpm/nprogress@0.2.0/node_modules/nprogress';
import './nprogress.css';
import UserLoading from 'D:/yinKeCode/encode-hooks-tag/encode-hooks-1.0copy/node_modules/.pnpm/dumi@2.4.20_@babel+core@7.27.1_eslint@8.57.1_prettier@3.5.3_react-dom@18.3.1_react@18.3.1_sty_uvz7eawcgpiiesnodpvqyjzx7a/node_modules/dumi/dist/client/pages/Loading';
import React, { useLayoutEffect, type FC } from 'react';
import { useSiteData } from 'dumi';

const DumiLoading: FC = () => {
  const { setLoading } = useSiteData();

  useLayoutEffect(() => {
    setLoading(true);
    nprogress.start();

    return () => {
      setLoading(false);
      nprogress.done();
    }
  }, []);

  return <UserLoading />
}

export default DumiLoading;
